version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  api:
    build: .
    volumes:
      - ./:/app
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+asyncpg://user:password@db:5432/db}
      SECRET_KEY: ${SECRET_KEY:-supersecret}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
